gcloud compute instances create $IC_VM_NAME \
--project=$GCP_PROJECT \
--zone=$IC_VM_ZONE \
--machine-type=$IC_VM_TYPE \
--network-interface=network-tier=PREMIUM,subnet=$IC_SUBNET \
--maintenance-policy=MIGRATE \
--provisioning-model=STANDARD \
--no-service-account \
--no-scopes \
--create-disk=auto-delete=yes,boot=yes,device-name=$IC_VM_NAME,image=projects/debian-cloud/global/images/debian-11-bullseye-v20220621,mode=rw,size=100,type=projects/$GCP_PROJECT/zones/$IC_VM_ZONE/diskTypes/pd-balanced \
--no-shielded-secure-boot \
--no-shielded-vtpm \
--no-shielded-integrity-monitoring \
--reservation-affinity=any